# Generated by Django 5.2.9 on 2025-12-22 20:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
        ('uploads', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='upload',
            options={'ordering': ['-uploaded_at']},
        ),
        migrations.AlterField(
            model_name='upload',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AddIndex(
            model_name='upload',
            index=models.Index(fields=['patient', '-uploaded_at'], name='uploads_upl_patient_f1dc4d_idx'),
        ),
        migrations.AddIndex(
            model_name='upload',
            index=models.Index(fields=['appointment', '-uploaded_at'], name='uploads_upl_appoint_b527e7_idx'),
        ),
        migrations.AddField(
            model_name='uploadreply',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upload_replies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='uploadreply',
            name='upload',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='uploads.upload'),
        ),
        migrations.AddIndex(
            model_name='uploadreply',
            index=models.Index(fields=['upload', 'created_at'], name='uploads_upl_upload__a4b488_idx'),
        ),
    ]
